py -2 jemdoc.py index.jemdoc
py -2 jemdoc.py exp.jemdoc
py -2 jemdoc.py edu.jemdoc
py -2 jemdoc.py overview.jemdoc
py -2 jemdoc.py jrnl.jemdoc
py -2 jemdoc.py conf.jemdoc
py -2 jemdoc.py res.jemdoc
py -2 jemdoc.py service.jemdoc
py -2 jemdoc.py outreach.jemdoc